[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.24"
optimizer = true
optimizer_runs = 200

[rpc_endpoints]
base = "${BASE_RPC_URL}"
base-sepolia = "${BASE_SEPOLIA_RPC_URL}"
polygon = "${POLYGON_RPC_URL}"
polygon-amoy = "${POLYGON_AMOY_RPC_URL}"
arbitrum-sepolia = "${ARBITRUM_SEPOLIA_RPC_URL}"
bsc-testnet = "${BSC_TESTNET_RPC_URL}"

[etherscan]
base = { key = "${BASESCAN_API_KEY}" }
base-sepolia = { key = "${BASESCAN_API_KEY}" }
polygon = { key = "${POLYGONSCAN_API_KEY}" }
polygon-amoy = { key = "${POLYGONSCAN_API_KEY}" }
arbitrum-sepolia = { key = "${ARBISCAN_API_KEY}", url = "https://api-sepolia.arbiscan.io/api" }
bsc-testnet = { key = "${BSCSCAN_API_KEY}", url = "https://api-testnet.bscscan.com/api" }
